title:          Napier Developers Society
description:    > 
      Napier Developers Society is a group of students who work together to develop
      fun projects and their skills. We have a very open attitude to ideas and welcome
      creativity from all of our members. Our goal is to have fun, to learn and help
      prepare people for their future in the industry.


url:            http://napierdevsoc.uk
baseurl:        

markdown:       rdiscount
permalink:      posts/:year/:month/:day/:title/
highlighter:    pygments
paginate:       10
paginate_path: "page-:num"
encoding:       UTF-8

exclude:        ["README.md", "CNAME", "Rakefile", "Gemfile", "Gemfile.lock", ".gitignore"]

github:   "https://github.com/NapierDevSoc"
gitter:   "https://gitter.im/NapierDevSoc"
facebook_page:  "https://www.facebook.com/napierdevelopers"
facebook_group: "https://www.facebook.com/groups/napierdevelopers/"

gems:
  - jekyll-sitemap
